### ISSUE TITLE
CREST run did not complete

### ISSUE THREAD

**Issue by ironlossli** [andrewtarzia/big_unsymm#1]
If I use XTB and CREST alone, it works fine
Unfortunately, I am now in trouble with the same problem.

Here's what I wrote about it

env_set

Output_file: 

 

 
[env_set output.zip](https://github.com/andrewtarzia/big_unsymm/files/9757178/env_set.output.zip)

![error](https://user-images.githubusercontent.com/77138601/195123418-e24ffad1-b7ab-4846-bd43-1acb2c1d0b36.PNG)

**Comment by andrewtarzia** [comment]
Hey @lihaoran-001 ,

Are there any output files in the output directory?

Is there any issue with losing ssh connection to a machine or anything like that?

Thank you,

Andrew

**Comment by ironlossli** [comment]
There are several files xtb.out crest.out lig_unopt.mol   
This software does not seem to run without running

**Comment by andrewtarzia** [comment]
What are the contents of `xtb.out` and `crest.out`?

**Comment by ironlossli** [comment]
![crest](https://user-images.githubusercontent.com/77138601/195136951-bbf3cda1-cfc7-4dac-81f3-0ae66e5fc726.PNG)
This is the crest.out
The contents of xtb is 0

**Comment by andrewtarzia** [comment]
It looks like the task stops for some reason - can you monitor the task in `top` or something like that to see that it actually runs?

**Comment by ironlossli** [comment]
I will try it

**Comment by ironlossli** [comment]
Thank you very much. 
According to your suggestion, I checked from the beginning and found the problem. When I checked it, I realized that crest had nothing to do with it. It was an error calling xtb.

**Comment by andrewtarzia** [comment]
Excellent! I will close this now, but I am curious to see how your research goes with this code and please join the stk discord, below, if you are interested in this methodology further!

https://discord.gg/26cdZBg3
